# Site settings
title: SamutSaring Bahay at Lupa
subtitle:
email: larrysuico2@gmail.com
description: Affordable House and Lot or Townhouses for sale in Rizal. Updated listing and status feel free to contact us for more information.
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
url: "https://samutsarihub.com/" # the base hostname & protocol for your site
author:
street_address: Driven HQ
city: Mandaluyong City
state: Metro Manila
zip_code: 1554
country: Philippines
phone: Globe 0956 227 5210
       Sun 0923 635 6242

# Social settings
facebook_url: https://facebook.com/samutsarihub/
googleplus_url: https://plus.google.com/u/0/b/104221817068710997861/
twitter_url: https://twitter.com/samutsarihub

# Sass building
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
